# Generated by Django 4.2.1 on 2023-07-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_balance_sheet_payments1_profit_loss_payments1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payrollemployee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False, verbose_name='EMPLOYEEID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('gsttype', models.CharField(max_length=100, null=True)),
                ('gstin', models.CharField(max_length=100, null=True)),
                ('panno', models.CharField(max_length=100, null=True)),
                ('openbalance', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('employees', models.CharField(max_length=100, null=True)),
                ('joindate', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=100, null=True)),
                ('salarydetails', models.CharField(max_length=100, null=True)),
                ('effectivefrom', models.CharField(max_length=100, null=True)),
                ('hours', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('employeeno', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('function', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('dateofbirth', models.CharField(max_length=100, null=True)),
                ('bloodgroup', models.CharField(max_length=100, null=True)),
                ('fathersmothersname', models.CharField(max_length=100, null=True)),
                ('spousename', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('generalemail', models.CharField(max_length=100, null=True)),
                ('generalphone', models.CharField(max_length=100, null=True)),
                ('bankdetails', models.CharField(max_length=100, null=True)),
                ('acno', models.CharField(max_length=100, null=True)),
                ('ifsccode', models.CharField(max_length=100, null=True)),
                ('bankname', models.CharField(max_length=100, null=True)),
                ('branchname', models.CharField(max_length=100, null=True)),
                ('transactiontype', models.CharField(max_length=100, null=True)),
                ('pannumber', models.CharField(max_length=100, null=True)),
                ('universalaccountnumber', models.CharField(max_length=100, null=True)),
                ('pfaccountnumber', models.CharField(max_length=100, null=True)),
                ('praccountnumber', models.CharField(max_length=100, null=True)),
                ('esinumber', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('shipstreet', models.CharField(max_length=100, null=True)),
                ('shipcity', models.CharField(max_length=100, null=True)),
                ('shipstate', models.CharField(max_length=100, null=True)),
                ('shippincode', models.CharField(max_length=100, null=True)),
                ('shipcountry', models.CharField(max_length=100, null=True)),
                ('payhead', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
