# Generated by Django 4.2.1 on 2023-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_payrollemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
