# Generated by Django 4.2.1 on 2023-07-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_payrollemployee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='payrollemployee'),
        ),
    ]
