# Generated by Django 4.2.1 on 2023-07-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_payrollemployee_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='comments',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
