# Generated by Django 4.2.1 on 2023-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_payrollemployee_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='company',
            new_name='tempcity',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='gstin',
            new_name='tempcountry',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='gsttype',
            new_name='temppincode',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='openbalance',
            new_name='tempstate',
        ),
        migrations.RenameField(
            model_name='payrollemployee',
            old_name='panno',
            new_name='tempstreet',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='shipcity',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='shipcountry',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='shippincode',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='shipstate',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='shipstreet',
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='adharnumber',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='file',
            field=models.FileField(default='', upload_to='payrollemployee'),
        ),
        migrations.AlterField(
            model_name='payrollemployee',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='images/'),
        ),
    ]
