# Generated by Django 4.2.1 on 2023-07-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_rename_company_payrollemployee_tempcity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='comments',
        ),
        migrations.CreateModel(
            name='payrollcomments',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False, verbose_name='COMMENTID')),
                ('comment', models.CharField(max_length=250, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee')),
            ],
        ),
    ]
