# Generated by Django 4.2.1 on 2023-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_remove_payrollemployee_comments_payrollcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='istds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tdstype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
