# Generated by Django 4.2.1 on 2023-07-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_payrollemployee_istds_payrollemployee_tds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='generalemail',
        ),
        migrations.RemoveField(
            model_name='payrollemployee',
            name='website',
        ),
    ]
