# Generated by Django 4.2.1 on 2023-08-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_remove_payrollemployee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts1',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
