# Generated by Django 4.2.1 on 2023-08-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_accounts1_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts1',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
